org: ignaciovidal
service: alerta-utec

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 1024
  timeout: 20
  environment:
    USERS_TABLE: t_users
    INCIDENTES_TABLE: t_incidentes
    HISTORIAL_TABLE: t_historial
    CONNECTIONS_TABLE: t_connections
    SNS_TOPIC: !Ref AlertaUTECSNSTopic
    JWT_SECRET: alerta-utec-secret-key-2024

functions:
  # ================== AUTHENTICATION ==============
  register_user:
    handler: Lambdas/Auth/register_user.lambda_handler
    events:
      - http:
          path: /usuarios/registro
          method: post
          cors: true

  login_user:
    handler: Lambdas/Auth/login_user.lambda_handler
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true

  validate_token:
    handler: Lambdas/Auth/validate_token.lambda_handler

  # ================= WEBSOCKETS ==================
  connect:
    handler: Lambdas/WebSockets/connect.handler
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: Lambdas/WebSockets/disconnect.handler
    events:
      - websocket:
          route: $disconnect

  default:
    handler: Lambdas/WebSockets/default.handler
    events:
      - websocket:
          route: $default

  notify_handler:
    handler: Lambdas/WebSockets/notify_handler.handler
    environment:
      WEBSOCKET_API_ID: ${env:WEBSOCKET_API_ID, ''}

  # =================== USERS ======================
  get_user_by_id:
    handler: Lambdas/User/get_user_by_id.lambda_handler
    events:
      - http:
          path: /usuarios/buscar
          method: get
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

  list_users:
    handler: Lambdas/User/list_users.lambda_handler
    events:
      - http:
          path: /usuarios/listar
          method: get
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

  # ================= INCIDENTS ===================
  create_incidente:
    handler: Lambdas/Incidentes/create_incidente.lambda_handler
    events:
      - http:
          path: /incidentes/crear
          method: post
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

  get_incidente_by_id:
    handler: Lambdas/Incidentes/get_incidente_by_id.lambda_handler
    events:
      - http:
          path: /incidentes/buscar
          method: get
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

  update_estado_incidente:
    handler: Lambdas/Incidentes/update_estado_incidente.lambda_handler
    events:
      - http:
          path: /incidentes/estado
          method: put
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

  # ================ HISTORIAL ===================
  list_historial:
    handler: Lambdas/Historial/list_historial.lambda_handler
    events:
      - http:
          path: /historial/listar
          method: get
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

  list_historial_by_incidente:
    handler: Lambdas/Historial/list_historial_by_incidente.lambda_handler
    events:
      - http:
          path: /historial/incidente
          method: get
          cors: true
          authorizer:
            name: validate_token
            resultTtlInSeconds: 0

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    IncidentesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_incidentes
        AttributeDefinitions:
          - AttributeName: codigo_incidente
            AttributeType: S
        KeySchema:
          - AttributeName: codigo_incidente
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        
    WebsocketTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_connections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    HistorialIncidenteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_historial
        AttributeDefinitions:
          - AttributeName: codigo_incidente
            AttributeType: S
          - AttributeName: uuid_evento
            AttributeType: S
        KeySchema:
          - AttributeName: codigo_incidente
            KeyType: HASH
          - AttributeName: uuid_evento
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    AlertaUTECSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: AlertaUTEC
        DisplayName: Notificaciones AlertaUTEC
